### ISSUE TITLE
Does openchat use a prompt template?

### ISSUE THREAD

**Issue by sz128** [imoneoi/openchat#10]
Great Works!

It seems that [openchat.train.json](https://huggingface.co/datasets/openchat/openchat_sharegpt4_dataset/blob/main/openchat.train.json) does not utilize a prompt template like what [alpaca-lora](https://github.com/tloen/alpaca-lora/tree/main/templates) does.

Do you make experiments about using a prompt template? Will that be better or not?

Thank you!

**Comment by imoneoi** [comment]
OpenChat added prompt templates during the dataset generation phase. So openchat.train.json already contains a template. Please have a look at openchat.[train/eval].text.json for a better explanation.

We haven't conducted ablation on the prompt template yet. You can do it yourself, about 3 hours of training with 8xA100. We welcome your contributions!

**Comment by imoneoi** [comment]
Closing this issue now. If you have further questions, plz re-open.
