### ISSUE TITLE
why openchat's name is ChatGPT

### ISSUE THREAD

**Issue by clouly** [imoneoi/openchat#100]
![image](https://github.com/imoneoi/openchat/assets/8359323/7ad949ce-d583-4ca3-930a-df8f481dbce0)

**Comment by LLjo** [comment]
check 
https://github.com/imoneoi/openchat/issues/78

**Comment by imoneoi** [comment]
Yes, please check https://github.com/imoneoi/openchat/issues/78. :smiley:
