### ISSUE TITLE
YI-34b Adapter

### ISSUE THREAD

**Issue by Ulov888** [imoneoi/openchat#110]
i tried your guys code, its work very well on llama or mistral, so i am trying to apply to more type of model,such as Yi-34b, which is also llama architectures.
<html>
<body>

{
--
  | "architectures": [
  | "LlamaForCausalLM"
  | ],
  | "attention_bias": false,
  | "bos_token_id": 1,
  | "eos_token_id": 2,
  | "hidden_act": "silu",
  | "hidden_size": 7168,
  | "initializer_range": 0.02,
  | "intermediate_size": 20480,
  | "max_position_embeddings": 4096,
  | "model_type": "llama",
  | "num_attention_heads": 56,
  | "num_hidden_layers": 60,
  | "num_key_value_heads": 8,
  | "pretraining_tp": 1,
  | "rms_norm_eps": 1e-05,
  | "rope_scaling": null,
  | "rope_theta": 5000000.0,
  | "tie_word_embeddings": false,
  | "torch_dtype": "bfloat16",
  | "transformers_version": "4.35.0",
  | "use_cache": true,
  | "vocab_size": 64000
  | }

</body>
</html>

i want to know why cant use the unpadded_llama.py to load Yi-34b weights, i comes out errors as following:
ValueError: Trying to set a tensor of shape torch.Size([1024, 7168]) in "weight" (which has shape torch.Size([7168, 7168])), this look incorrect.

**Comment by imoneoi** [comment]
It's because the current Llama implementation doesn't support GQA. You can try applying this PR https://github.com/imoneoi/openchat/pull/115
