### ISSUE TITLE
Question about batch_max_len

### ISSUE THREAD

**Issue by jujeongho0** [imoneoi/openchat#113]
Thanks for Great Work!!!
I've been trying to train and have a question.

The dataset is divided by multipack_dataloader by the size of batch_max_len, and this data goes into the model as input.

However, instead of being organized as a batch size, they seem to be attached as a one-dimensional array of size batch_max_len and being input to the model, so if batch_max_len is larger than the length of tokens that can be input to the model, won't it be impossible to learn?

For example, if the model I want to train has an input token length of 2048 and I set batch_max_len to 83968, won't the model be unable to accept data of this size as input?

++ The model I'm trying to train is a GPT-J structure, so I need to write new unpadded model code, do you have any plans to write for the gpt-j structure?

**Comment by imoneoi** [comment]
We use FlashAttention 2 `varlen` API. It'll identify different sequences in the 1D array by `cu_seqlens` and `max_seqlen` field, and process each sequence independently. You can refer to [this function](https://github.com/imoneoi/openchat/blob/master/ochat/training_deepspeed/train.py#L112).

To answer your question regrading GPT-J, it's analogous to Llama and Mistral, with a bit difference in the Transformer architecture. You can adapt the code [here](https://github.com/imoneoi/openchat/blob/master/ochat/models/unpadded_llama.py) to fit GPT-J architecture.

**Comment by jujeongho0** [comment]
I completely understand.
Thank you for your kind reply :)
