### ISSUE TITLE
gradio demo

### ISSUE THREAD

**Issue by AK391** [imoneoi/openchat#14]
would be great to setup a gradio demo for this on huggingface, similar to https://huggingface.co/spaces/mosaicml/mpt-30b-chat, this is the guide: https://huggingface.co/docs/hub/spaces-sdks-gradio

**Comment by imoneoi** [comment]
Already working in progress :)

**Comment by imoneoi** [comment]
Demo now online!

OpenChat UI: https://openchat.team
HF Spaces gradio: https://huggingface.co/spaces/openchat/OpenChat_3.2

**Comment by yvrjsharma** [comment]
Great work @imoneoi ! Would it be possible to link the Gradio demo locally on the repo?
