### ISSUE TITLE
Met error of CUDA out of memory.  How to split the model into multiple GPUs?

### ISSUE THREAD

**Issue by permissionx** [imoneoi/openchat#16]
When loading the checkpoint, it comes out:
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 15.90 GiB total capacity; 15.30 GiB already allocated; 31.81 MiB free; 15.30 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by imoneoi** [comment]
Currently, the tensor parallel functionality is not supported. We will release the V2 version which includes vLLM inference server and tensor parallel recently. Stay tuned!

**Comment by leonholub** [comment]
I know i'm too late on this issue as it's already closed but i cannot find the hardware requirements to run it. How much RAM and GPU RAM is needed or recommended for running openchat?

**Comment by imoneoi** [comment]
We recommend having a GPU with memory of at least 40GB (1x A100) to run the server

**Comment by talhaanwarch** [comment]
> We recommend having a GPU with memory of at least 40GB (1x A100) to run the server

@imoneoi please add the clearly in readme.

**Comment by Altenrion** [comment]
> We recommend having a GPU with memory of at least 40GB (1x A100) to run the server

1) This is super unclear in Readme. 
2) Does this mean that this project can NOT be started as server on Tesla T4 16 GB or P40 24Gb ?
