### ISSUE TITLE
did ```calculate_auto_lr``` affect a lot?

### ISSUE THREAD

**Issue by fpcsong** [imoneoi/openchat#162]
RT

**Comment by imoneoi** [comment]
Sorry, what do you mean? This function is for calculating the learning rate based on the batch size using square root rule, as mentioned in the README.

**Comment by fpcsong** [comment]
Sorry for not making it clear, I wonder if the square root rule has a big impact on the results, compared to other lr scheduler(cosine?)

**Comment by imoneoi** [comment]
It's using the cosine scheduler. The square root rule is used for calculating initial lr for the schedule, otherwise we need to manually tune it.

**Comment by fpcsong** [comment]
Thank you~
