### ISSUE TITLE
Troubleshooting OpenChat and Non-English Data in the Dataset

### ISSUE THREAD

**Issue by yifan123** [imoneoi/openchat#17]
Great job! I have a few questions:

1. I'm using the following script to test OpenChat, but even with the correct prompt template, the output is not very accurate. How should I modify the testing code?

   ```python
   tokenizer = LlamaTokenizer.from_pretrained(args.model_name_or_path, fast_tokenizer=False)
   model = create_hf_model(AutoModelForCausalLM, args.model_name_or_path, tokenizer, None)
   prompt = "<s>Human:  What are all the pairs of natural numbers which sum to 6?<|end_of_turn|>Assistant: "
   generation_config = GenerationConfig(max_new_tokens=2048,num_beams=1,do_sample=True,temperature=0.7,top_p=0.9)
   generate_ids = model.generate(input_ids=inputs.input_ids,generation_config=generation_config,)
   response = tokenizer.batch_decode(generate_ids,skip_special_tokens=True,clean_up_tokenization_spaces=False)[0]
   print(response)
   ```
output:
![image](https://github.com/imoneoi/openchat/assets/37578514/add04fd1-9b91-4ff1-88a7-2e6f209e88ce)
   

2. I noticed that there is a lot of non-English data in the dataset, which obviously wouldn't benefit the performance of alpaca_eval. Why not filter out this data?
https://huggingface.co/datasets/openchat/openchat_sharegpt4_dataset/blob/main/openchat.train.text.json
![image](https://github.com/imoneoi/openchat/assets/37578514/563ceaab-6e40-4f7a-b183-bdb5f01b7bd9)

**Comment by imoneoi** [comment]
1. The conversation template involves concatenating tokens, and cannot be expressed by plain text. You can try the following code:

```python
def tokenize_single_input(tokenizer, prompt):
    human_prefix = "Human: "
    ai_prefix  = "Assistant: "
    eot_token = "<|end_of_turn|>"
    bos_token = "<s>"

    def _tokenize(text):
        return tokenizer.convert_tokens_to_ids(tokenizer._tokenize(text))

    def _tokenize_special(special_name):
        return tokenizer.convert_tokens_to_ids(special_name)
    
    return [_tokenize_special(bos_token)] + _tokenize(human_prefix) + _tokenize(prompt) + [_tokenize_special(eot_token)] + \
           _tokenize(ai_prefix)

``` 

P.S. The current version of OpenChat is good at general questions, but poor at mathematics and reasoning, limited by the foundation model. We will improve reasoning and math skills in future versions.


2. Filtering may improve baseline performance, but we want the model to retain basic multilingual capabilities (although LLaMA was not trained on languages other than English). In the future, we may consider filtering languages.

**Comment by imoneoi** [comment]
Closing this issue now. If you have further questions, plz re-open.
