### ISSUE TITLE
Reproduce Training Data

### ISSUE THREAD

**Issue by bpucla** [imoneoi/openchat#18]
To reproduce the training data, we need ShareGPT htmls as stated in 
`The input folder should contain a ShareGPT folder with .html files for each ShareGPT conversation page inside.`

It seems that the best ShareGPT source I can find online is [here](https://huggingface.co/datasets/anon8231489123/ShareGPT_Vicuna_unfiltered/tree/main/HTML_cleaned_raw_dataset). However, it doesn't give model information and thus we have no way to filter for GPT4 responses. 

Any pointers or hints on how to get GPT4 responses would be appreciated!

**Comment by imoneoi** [comment]
We provide a "sharegpt_clean.json" containing about 80K conversations, which contains a "model" field that can be used to filter GPT4 responses.
