### ISSUE TITLE
 repeat the output content until the maximum output length is set

### ISSUE THREAD

**Issue by zestaken** [imoneoi/openchat#209]
Using Openchat-3.5-0106 locally will repeat the output content until the maximum output length is set.  In other words, the output of the model does not stop automatically.
And the model is loaded with the following warning:
`Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.`
May I ask how to solve this kind of problem?

**Comment by imoneoi** [comment]
Hi @zestaken, can you provide more information about your local model setup?

**Comment by Cancerxy** [comment]
I also encountered this problem

**Comment by 1193700079** [comment]
I also encountered this problem
