### ISSUE TITLE
Can you please update requirements.txt file with versions

### ISSUE THREAD

**Issue by talhaanwarch** [imoneoi/openchat#21]
I am getting different errors. For example 
AssertionError: pydantic.dataclasses.dataclass only supports init=False

I have to downgrade pydantic version. It would be great if you can add all packages versions

**Comment by talhaanwarch** [comment]
Another error
RuntimeError: Failed to load the tokenizer. If you are using a LLaMA-based model, use 'hf-internal-testing/llama-tokenizer' 
instead of the original tokenizer.

Iinstalled pip install protobuf==3.20.0 -U to resolve this

**Comment by imoneoi** [comment]
We've fixed the dependencies and released a pip package. Tested the following setup.

```
conda create -y --name openchat
conda activate openchat

conda install -y python
conda install -y cudatoolkit-dev -c conda-forge
pip3 install torch torchvision torchaudio

pip3 install packaging ninja
pip3 install --no-build-isolation "flash-attn<2"

pip3 install ochat
```

If there are still problems, please re-open this issue.
