### ISSUE TITLE
A question about the prefix of only SFT 

### ISSUE THREAD

**Issue by RikkiXu** [imoneoi/openchat#211]
hi, thank your excellent job! 
I would like to ask if the template of **only SFT** in your paper contains prefix, such as User/Assistant. 

The code is in this [url] (https://github.com/imoneoi/openchat/blob/f528c2716f644777c5cbfa6c73aa167de50250ce/ochat/config/conversation_template.py#L91C1-L92C1)

**Comment by imoneoi** [comment]
Yes, it contains the role prefix. However, conditions such as `GPT3` / `GPT4` are removed. The resulting role prefixes are `User: ` and `Assistant: `
