### ISSUE TITLE
Does '~80K cleaned ShareGPT data' refer to ' sharegpt_clean.json' files in the 'openchat/openchat_sharegpt4_dataset'?

### ISSUE THREAD

**Issue by wn1652400018** [imoneoi/openchat#22]
And can you describe the details of  a conditioning strategy and weighted loss?
Thanks!

**Comment by imoneoi** [comment]
Yes, you are right. The conditioning strategy is relatively simple, assigning different prefixes for GPT3.5 and GPT4, and is implemented [here](https://github.com/imoneoi/openchat/blob/master/ochat/config/model_config.py#L74C23-L74C23). The training weighted loss is implemented [here](https://github.com/imoneoi/openchat/blob/master/ochat/training_deepspeed/train.py#L144), similar to label balancing in computer vision.
