### ISSUE TITLE
How to user llama_convert_and_add_eot_token.py script?

### ISSUE THREAD

**Issue by tsh78c9jk9** [imoneoi/openchat#23]
Before training the model, do I need to use the llama_convert_and_add_eot_token.py script first, and how should I use it?

Thanks!

**Comment by imoneoi** [comment]
Sorry for the inconvenience. It's similar to huggingface llama converter. 

```
python llama_convert_and_add_eot_token.py --input_dir ./models --model_size 13B --output_dir ./hf_models/LLaMA_13B_with_EOT --add_tokens \<\|end_of_turn\|\>
```

BTW, I uploaded converted Llama and Llama 2 with EOT token [here](https://huggingface.co/imone).
