### ISSUE TITLE
AssertionError: pydantic.dataclasses.dataclass only supports init=False

### ISSUE THREAD

**Issue by inlucru** [imoneoi/openchat#25]
i tried everything, from using docker (gives error about vllm) to venv and conda env, this is the last error i get, do you guys have idea what should i do?

File "/home/user/miniconda3/envs/venv/lib/python3.11/site-packages/pydantic/dataclasses.py", line 139, in dataclass
    assert init is False, 'pydantic.dataclasses.dataclass only supports init=False'
           ^^^^^^^^^^^^^
AssertionError: pydantic.dataclasses.dataclass only supports init=False

**Comment by imoneoi** [comment]
Have you solved the problem? It seems to be [a compatibility issue of Ray](https://discuss.ray.io/t/pydantic-dataclasses-dataclass-only-supports-init-false/11278).

**Comment by imoneoi** [comment]
Closing this issue now. If you have further questions, plz re-open.
