### ISSUE TITLE
Can not reproduce the alpaca_eval results of openchat v1

### ISSUE THREAD

**Issue by Yuanhy1997** [imoneoi/openchat#29]
I downloaded the provided openchat v1 model on huggingface through this model name 'openchat/openchat' and I use your model to predict the 805 evaluation queries of alpaca-eval and I can only get a win rate over davince-003 around 70 which is far from your reported number. The alpaca-eval is verified as having no bugs since I can reproduce the scores of other LLMs.

FYI, I set the query template to " Human: {query} <|end_of_turn|> Assistant: "  and I am using top_p sampling with top_p=1.0, temperature=0.7 and the maximum overall token length to 2048, which are consistent with the configs from this link: https://github.com/tatsu-lab/alpaca_eval/blob/main/src/alpaca_eval/models_configs/openchat-13b/configs.yaml
I also find out that the prompt from https://github.com/tatsu-lab/alpaca_eval/blob/main/src/alpaca_eval/models_configs/openchat-13b/prompt.txt is not consistent with the huggingface model and the training data provided. 

Can you kindly explain this performance discrepancy? Or maybe can you provide a script for openchat inference?

**Comment by imoneoi** [comment]
One possible reason is that the template is not plain text, but a concatenation of tokens. You can try the server provided in this repository with the `openai` interface configured by alpaca_eval

**Comment by Yuanhy1997** [comment]
Sorry, what do you mean by " is not plain text, but a concatenation of tokens.". I have made sure that the template text will be tokenized to the same token sequence as the tokenized training data provided. Can you just provide the template you use and the generation configs? I double-check the configs from your code here https://github.com/imoneoi/openchat/blob/master/ochat/config/model_config.py I think I use a consistent setting with your code based but the discrepancy is just so notable.

**Comment by imoneoi** [comment]
Have you tried using my conversation template code? https://github.com/imoneoi/openchat/blob/master/ochat/config/model_config.py

**Comment by imoneoi** [comment]
I have tried OpenAI API-compatible server on OpenChat V2-W. The win rate difference is about +/- 1%.

**Comment by imoneoi** [comment]
Closing this issue now. If you have further questions, plz re-open.
