### ISSUE TITLE
Can I use system prompt when training?

### ISSUE THREAD

**Issue by chuan298** [imoneoi/openchat#35]
Hi @imoneoi , I want my assistant to have different emotions or it can act as someone based on system prompt. So when training can I use data samples of the form `{system_prompt} Human: {human_message} <|end_of_turn|>Assistant: {assistant_message} ....` or such prompts are used in `{human_message}` like data samples you trained? Thank you!
Example: `<s>Human:  Act as SEO expert. I want you to create the best meta descriptions among my competitors.\n\nHere are the list of our competitor's meta descriptions. \n\n\nHere is my meta description. Revise it. I don't want NFT in my description. I do not offer any staking service. \n\nBuy and sell the world's largest selection of 10,000+ Cryptocurrencies<|end_of_turn|>Assistant:  ....`
Convert to `<s>Act as SEO expert. I want you to create the best meta descriptions among my competitors <|end_of_turn|>Human: Here are the list of our competitor's meta descriptions. \n\n\nHere is my meta description. Revise it. I don't want NFT in my description. I do not offer any staking service. \n\nBuy and sell the world's largest selection of 10,000+ Cryptocurrencies<|end_of_turn|>Assistant:  ....`

**Comment by imoneoi** [comment]
Yes. For training, `generate_conversation_template` has a `system_prompt` parameter, which will concatenate the system prompt using the same method you described. To use our model, you can add a system prompt before the user's first message, as shown below.

![Screenshot from 2023-08-04 23-07-31](https://github.com/imoneoi/openchat/assets/26354659/5ada0a70-c0f3-434e-a21a-1f0d554a064b)

**Comment by chuan298** [comment]
thank you @imoneoi
