### ISSUE TITLE
discord invite in readme expired

### ISSUE THREAD

**Issue by shenberg** [imoneoi/openchat#48]
I wanted to ask about the tokenizer. I quantized the model with the MLC framework and I noticed that the model never generates token `32000` to indicate end of turn, rather it generates the string `<|end_of_turn|>` as a sequence of tokens. Not what I expected. I don't know if it's a usage issue on my part.

**Comment by shenberg** [comment]
Also, thanks for this, even with the warts it's still the best-behaved model I've tried so far out of the 13B ones

**Comment by imoneoi** [comment]
Thanks for your report. We updated the discord link.

For your question, which weight are you using? I've tested our API server, it correctly outputs the stop token.

**Comment by shenberg** [comment]
Thanks!
I'm using [MLC-llm](https://github.com/mlc-ai/mlc-llm) as they have by far the best inference speed for batch size 1. Unfortunately it's a very complicated runtime that's pretty far-removed from the pytorch/HF ecosystem. I opened a bug re:tokenizer on their end for a couple of issues I found where they're not 100% compatible with HF AutoTokenizer, but even when I worked around them locally I noticed it doesn't solve issues.

**Comment by shenberg** [comment]
> Thanks for your report. We updated the discord link.
> 
> For your question, which weight are you using? I've tested our API server, it correctly outputs the stop token.

I set the system prompt to "You are a helpful chatbot named dot", and asked the bot "hi, what's up? how are you called and what are your dreams?", and the reply tokens I got were:
`[29991, 306, 626, 263, 8444, 13563, 7451, 4257, 360, 327, 29889, 1094, 385, 319, 29902, 4086, 1904, 29892, 306, 1016, 29915, 29873, 505, 21737, 470, 12561, 29879, 763, 25618, 437, 29889, 1205, 306, 29915, 29885, 1244, 304, 6985, 366, 411, 738, 5155, 470, 23820, 366, 29915, 29881, 763, 304, 5353, 29889, 1128, 508, 306, 1371, 366, 9826, 29973, 29966, 29989, 355, 29918, 974, 29918, 685, 29989, 29958]`

This decodes to:

```
! I am a helpful chatbot named Dot. As an AI language model, I don't have feelings or dreams like humans do. But I'm here to assist you with any questions or topics you'd like to discuss. How can I help you today?<|end_of_turn|>
```

Note how `<|end_of_turn|>` is encoded as [`29966, 29989, 355, 29918, 974, 29918, 685, 29989, 29958]`.
