### ISSUE TITLE
openchat_v3.2_super deployment to SageMaker doesn't work

### ISSUE THREAD

**Issue by ErdincWand** [imoneoi/openchat#50]
Hi team, 

I would like to deploy new model to AWS Sagemaker with below code and getting `RuntimeError: weight model.layers.0.self_attn.rotary_emb.inv_freq does not exist` seems something is missing in the model index. At least, I couldn't find it in https://huggingface.co/openchat/openchat_v3.2_super/blob/main/pytorch_model.bin.index.json

Thanks in advance for your help!

Here is the `deploy.py`
```
import json
import sagemaker
import boto3
from sagemaker.huggingface import HuggingFaceModel, get_huggingface_llm_image_uri

try:
	role = sagemaker.get_execution_role()
except ValueError:
	iam = boto3.client('iam')
	role = iam.get_role(RoleName='role-name')['Role']['Arn']

# Hub Model configuration. https://huggingface.co/models
hub = {
	'HF_MODEL_ID':'openchat/openchat_v3.2_super',
	'SM_NUM_GPUS': json.dumps(4)
}



# create Hugging Face Model Class
huggingface_model = HuggingFaceModel(
	image_uri=get_huggingface_llm_image_uri("huggingface",version="0.9.3"),
	env=hub,
	role=role, 
)

# deploy model to SageMaker Inference
predictor = huggingface_model.deploy(
	initial_instance_count=1,
	instance_type="ml.g5.12xlarge",
    endpoint_name="openchat-v3-2-super",
	container_startup_health_check_timeout=600,
  )
  
# send request
predictor.predict({
	"inputs": "My name is Julien and I like to",
})

**Comment by imoneoi** [comment]
This is because of some optimizations for padding-free training, the missing weights can be safely ignored and just let HF initialize them. You can set the ignore missing weights flag.
