### ISSUE TITLE
Persian language performance 

### ISSUE THREAD

**Issue by eyousefifar** [imoneoi/openchat#69]
The Open Chat demo appears to have limited support for Persian, and it has poor performance. It appears that the base models have not been trained with Persian data.

Would fine-tuning the Open Chat model using a Persian dataset improve its performance for Persian conversations?
Alternatively, should I seek a model that has been pre-trained on the Persian language?

**Comment by imoneoi** [comment]
Perhaps. OpenChat is based on Mistral, which may be trained on only a small amount of multilingual data.

To your question, yes, fine-tuning can improve performance in some languages (like Persian). Besides, using a pre-trained model on Persian might also perform better.
