### ISSUE TITLE
Windows WSL Tutorial, API Server - Nothing to Operational

### ISSUE THREAD

**Issue by RevolvingDCON** [imoneoi/openchat#71]
# **Using WSL 1.x, Ubuntu 22.04.3 LTS**
_This tutorial assumes you've already installed WSL and have a basic understanding of how it works_

`sudo apt update` - update packages
`sudo apt install build-essential` - install essentials

`sudo apt install -y curl` - Install curl
`curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh` - download miniconda
`bash miniconda.sh` - install miniconda, (you will need to accept terms)

Restart terminal (thank you windows)

`conda create -y --name openchat python=3.11` - create conda environment with python
`conda activate openchat` - enter environment

`pip3 install ochat` - install ochat (alternatively you can just pull the repo and build from source)

**Only one of the following is required to boot:**
`python -m ochat.serving.openai_api_server --model openchat/openchat_3.5` - single GPU boot

`python -m ochat.serving.openai_api_server --model openchat/openchat_3.5 --tensor-parallel-size 1` - single GPU boot if the above command doesn't work

Add `--api-keys YOUR_KEY` to the above launch command if it tells you too

If all goes well and it doesn't explode, you should have a web server listening on http://localhost:18888

**Comment by imoneoi** [comment]
Thank you for your contribution! Would you mind testing the following commands on your WSL? (it seems pytorch can be installed automatically) I'll update the instructions.

```
sudo apt update
sudo apt install build-essential

conda create -y --name openchat python=3.11
conda activate openchat

pip3 install ochat
```

**Comment by RevolvingDCON** [comment]
Hi, I've tested the above commands on a fresh WSL distro and was able to get it to run with substantially less commands. Thank you for pointing this out! I've updated my original post to reflect the changes.

Would you like me to create a pull request adding a WSL tutorial to the readme?

**Comment by imoneoi** [comment]
> Hi, I've tested the above commands on a fresh WSL distro and was able to get it to run with substantially less commands. Thank you for pointing this out! I've updated my original post to reflect the changes.
> 
> Would you like me to create a pull request adding a WSL tutorial to the readme?

Yeah, welcome!
