### ISSUE TITLE
Possible to get NVIDIA GeForce RTX 2070 working?

### ISSUE THREAD

**Issue by RandyLoeb** [imoneoi/openchat#73]
After running python3 -m ochat.serving.openai_api_server --model openchat/openchat_3.5
I get:

ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your NVIDIA GeForce RTX 2070 GPU has compute capability 7.5.

Any suggestions, thanks.

**Comment by RandyLoeb** [comment]
--dtype="half" got me past that error

**Comment by Altenrion** [comment]
@RandyLoeb have you ran into Out of memory iisues or like that? 
If yes - how have you solved that? 

I tries to start this OpenChat on 1080 8GB & T4 16GB GPU s with no luck.
