### ISSUE TITLE
In the online demo are we chatting with GPT-4 or OpenChat?

### ISSUE THREAD

**Issue by treya-lin** [imoneoi/openchat#78]
Hi  I'm a bit confused. 

I just checked out the online demo, and it offered only one model option (openchat aura), and when I asked it what model it was, it said it was actually GPT-4, and when I clicked the button for checking account balance, it redirected to openai's website. 
At the beginning, I thought OpenChat had been trained from scratch by the developer and was different from openai's model. But now it seems it is still using open ai's api services?

**Comment by imoneoi** [comment]
It's OpenChat 3.5. Our frontend is a forked version of ChatGPT UI (openchat-ui) interfacing with the openchat server.

**Comment by codebanesr** [comment]
If you want to be sure what model is being used, Just ask the model to write something gpt 4 wouldn't.  Like insult my ex manager. 

It's not gpt-4, and this model is also incredebly fast and accurate

**Comment by Aspie96** [comment]
I think it'd be really helpful to update the fork so that it reports accurate information.

**Comment by dub713** [comment]
![openchat_cray](https://github.com/imoneoi/openchat/assets/33442135/3b87eaae-c8c7-44ff-be41-72db17fbe6f9)

**Comment by Aspie96** [comment]
You should never expect LLMs to have knowledge of themselves.

This just shows that there is likely ChatGPT-generated text in the dataset, not that you are talking to ChatGPT.

It'd be interesting to know how to solve this problem and give models configurable self-knowledge, but the model is not ChatGPT here.

**Comment by kientv** [comment]
Why you need to config OpenAI API key here?   
![Uploading Screenshot_2023-12-05-01-44-52-41.jpg…]()

**Comment by Kvisaz** [comment]
If it is really Open Chat - it is very impressive!
I see no other 7B models with such high non-english language quality
