### ISSUE TITLE
TensorRT LLM support (Uninitialized Weights When Building OpenChat 3.5 Model)

### ISSUE THREAD

**Issue by tsathya98** [imoneoi/openchat#92]
First of All,
I am currently utilizing the remarkable OpenChat 3.5 model for its impressive performance in language modeling tasks. However, I have encountered a challenge while trying to leverage NVIDIA TensorRT for inference acceleration.

#### Steps to Reproduce
- I combined two split binary weight files into a single `pytorch_model.bin` as required by the TensorRT build process within the provided TensorRT Docker environment.
Combining BIN files code:
```
import os
import torch
import json

def combine_model_bins(model_dir, index_file, bin_files, output_file):
    with open(os.path.join(model_dir, index_file), 'r') as f:
        index_data = json.load(f)
    partial_state_dicts = {}
    for bin_file in bin_files:
        partial_state_dict = torch.load(os.path.join(model_dir, bin_file), map_location='cpu')
        partial_state_dicts[bin_file] = partial_state_dict
    complete_state_dict = {}
    for weight_name, bin_file in index_data['weight_map'].items():
        complete_state_dict[weight_name] = partial_state_dicts[bin_file][weight_name]
    torch.save(complete_state_dict, os.path.join(model_dir, output_file))

model_dir = '/'  
index_file = 'pytorch_model.bin.index.json' 
bin_files = ['pytorch_model-00001-of-00002.bin', 'pytorch_model-00002-of-00002.bin'] 
output_file = 'combined_pytorch_model.bin' 
combine_model_bins(model_dir, index_file, bin_files, output_file)

```
- I tested the single BIN file with OpenChat Server and I am getting the same inference output with 2 bin and 1 bin files.
- I followed the TensorRT build instructions to construct the model.
- Upon execution, I observed that certain layer weights are not being initialized (image attached with this issue)

#### Current Behavior
The model initializes without errors, but some layer weights are reported as uninitialized. (Please find the attached screenshot for the specific layers.)
![openchat_tensorRT](https://github.com/imoneoi/openchat/assets/50142667/f2d3ebc7-b65d-40fa-8855-c162d3ff194d)

#### Expected Behavior
All layer weights should be initialized correctly when building the model using NVIDIA TensorRT to ensure optimal performance and utilization of TensorRT's capabilities.

#### Additional Context
I am unsure if there is existing support for NVIDIA TensorRT within OpenChat 3.5, and if so, I might be missing some steps or requirements to achieve a successful build. If there is no current support, I would like to inquire about the potential timeline for its implementation.

I would greatly appreciate any guidance or resources you could provide on utilizing NVIDIA TensorRT with OpenChat 3.5, including documentation or examples if available.

Thank you for your time and assistance.

Best regards,
Sathya T

**Comment by imoneoi** [comment]
Hi, can you try running it despite the warning? The uninitialized `inv_freq` warning can be safely ignored in many cases.

**Comment by tsathya98** [comment]
> Hi, can you try running it despite the warning? The uninitialized `inv_freq` warning can be safely ignored in many cases.

Thank you!
I ignored the warnings and was able to convert the model using TensorRT Int-8 quantization

**Comment by tsathya98** [comment]
Issue Resolved
