### ISSUE TITLE
Why in the fastchat project, using the openchat_3.5 model, inference is very slow, much slower than vicuna-13b-v1.5

### ISSUE THREAD

**Issue by xiaocode337317439** [imoneoi/openchat#95]
Why in the fastchat project, using the model, inference is very slow, much slower than vicuna-13b-v1.5, is it special? The 7b model is supposed to be faster than the 13b model, but it is not.

**Comment by imoneoi** [comment]
Is it because of the sliding window attention in Mistral architecture? You can try vLLM worker in fastchat or post an issue there.

**Comment by imoneoi** [comment]
Can you post the detailed error message? We tried vLLM worker and it is fine.
