### ISSUE TITLE
Calculation in a 'weighted_cross_entropy'

### ISSUE THREAD

**Issue by jujeongho0** [imoneoi/openchat#99]
Hi.
Thanks for the good work.

I was going through the code and had a question about the 'weighted_cross_entropy' calculation, so I decided to leave an issue.

When calculating loss using cross_entropy, you gave reduction as none to multiply by weight, and after multiplying by weight, you used sum() instead of mean(), which is different from the original formula, and I was wondering why?

Thank you :)

**Comment by imoneoi** [comment]
We divide the final loss by the total number of tokens on all GPUs in `train.py`. You can check https://github.com/imoneoi/openchat/issues/74 for details :hugs:

**Comment by jujeongho0** [comment]
Thank you for your kind response 👍 
Close issue.
